### ISSUE TITLE
SALT indexing non-standard needs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-exhibits-template#28]
what does SALT need in spotlight to have parity with old SALT?

would profiling the MODS help w this?

**Comment by ndushay** [comment]
Facet Parity issues:
  - [ ] Author:  old:  first last;   spotlight:  last, first
  - [ ] Organization:   comma separated data in MODS not parsed as separate values
   e.g.  http://purl.stanford.edu/vw282gv1740.mods  with <note displayLabel="Donor tags">Knowledge Systems Laboratory, medical applications, Publishing, Stanford, Stanford Computer Science Department</note>
  - [ ] Resource Type / Document Type:  diff values (diff algorithm)
  - [ ] Year / Date:  is the algorithm to get the date the same?

  not avail via current spotlight
    - [ ] Person
    - [ ] City 
    - [ ] Corporate Entity
    - [ ] Company
    - [ ] Series
    - [ ] Box
    - [ ] Folder
   - [ ] Tagged by Donor ... unless this is Topic in spotlight facets

**Comment by ndushay** [comment]
Accession record for comparison in search results:   dk023cx0427  ("ARPA Management Report - Bibliography for ARPA Report")

Search result list view:  
 - [ ] saltworks shows location:  need to ensure mods physicalLocation with box number is acceptable and that we can get it displayed in search results

**Comment by ndushay** [comment]
Sort Parity:  looks fine to me

**Comment by ndushay** [comment]
Searching parity:  need all docs w mods to do A:B acceptance testing.  (Could even code this w rspec-solr if we need to ...)

**Comment by ndushay** [comment]
There is a sort of linked view of the series doc in upper left nav when looking at a single document  (e.g. an outline of the documents in the relevant series, with links like facets) -- @ggeisler @peetucket is this expected for parity?

Indexing would be required, I imagine ...

**Comment by ndushay** [comment]
doc view:  note blue box with facet-like links, and facets on single doc view.

![saltworks doc view](https://cloud.githubusercontent.com/assets/96775/10443028/657b0208-710d-11e5-9fa1-299693215531.png)

**Comment by ggeisler** [comment]
@ndushay: I think @snydman and/or @peetucket are the ones to answer whether the blue box content is a required component of parity, but in my opinion we shouldn't try to do this in Spotlight. It assumes a finding aid/hierarchical document structure that to my knowledge we are not targeting for support in Spotlight. (This is the sort of feature ArcLight *would* have, because ArcLight will be intended specifically to provide richer access to finding aid/hierarchical documents.)

I also don't think we should change the Spotlight Item Detail page (single doc view, item show page) just because SALT shows the matched facet values in that view. Again, I'm not the one to make the decision, but in my opinion this doesn't have enough utility to warrant changing the way Spotlight does things.

**Comment by cbeer** [comment]
:+1: I agree that it feels out-of-scope. We can do lightweight arrangement using pages and browse categories, and probably create a better user experience than saltworks currently provides.

If we need more interesting arrangement data, I think we ought to revisit the MODS mapping to get an approach for parsing box info that will work across other collections.

**Comment by snydman** [comment]
Blue box is definitely out of scope and we do not make any extra efforts to browse inside the box.

**Comment by peetucket** [comment]
What @snydman said.  Not necessary for feigenbaum.

**Comment by peetucket** [comment]
It looks like the current saltworks "Year" facet is what we have in the spotlight "Date" facet, so we just need to rename the spotlight facet from "Date" to "Year".  Bonus points if we can drop in the date-slider a la Revs and BV.

**Comment by cbeer** [comment]
Do we need to rename the facet? Would a user really care?

**Comment by peetucket** [comment]
Isn't it easy to rename facets in Spotlight?  I would rename just to keep parity.  I assume the label "Year" was chosen deliberately when the saltworks site was setup X years ago.

**Comment by cbeer** [comment]
The curator can certainly do it, I'm just asking if it actually important. "Date" is good enough for searchworks, and seems like it's more representative of our current thinking than such an old site.

**Comment by cbeer** [comment]
Maybe my higher level concern is: I think we should be wary of trying for perfect parity. The saltworks site has a very small user base, and we should make good decisions for the Feigenbaum exhibit instead of trying to replicate details.

**Comment by ndushay** [comment]
closing this in favor of #38, #39 and #40
