### ISSUE TITLE
Update project dependencies to the latest and greatest

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-exhibits-template#29]

**Comment by peetucket** [comment]
does this basically mean bundle update and be sure tests pass?  to me it looks like everything is already up to date...

**Comment by cbeer** [comment]
That, and unpin and upgrade dependencies as appropriate, e.g.:

```
gem "bootstrap-sass", "3.3.3" # pending twbs/bootstrap-sass#873
```

Can probably get updated to the latest `bootstrap-sass`

and:

```
gem "blacklight", git: "https://github.com/projectblacklight/blacklight" # "~> 5.10"
```

Probably can pin to `blacklight ~> 5.15`.

There's also some pinning in the spotlight gemspec that we should work on too (and there's an appropriate ticket there too..)
