### ISSUE TITLE
SALT indexing:  display location parity

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-exhibits-template#40]
Show separate display fields for box, folder and series on item detail page.
These will be the same as the facetable values.
![search results list view](https://cloud.githubusercontent.com/assets/96775/10443070/02b72e20-710e-11e5-97f3-63517a3ce134.png)

**Comment by peetucket** [comment]
We do not need to display in search results.  We should display in record view.

**Comment by peetucket** [comment]
Think about design for how to display physical location in the record detail view.  We will have fields separated for faceting but we can morph back into a single display string to make it look better.  e.g note on the current SaltWorks site how the record view shows each facet value separately: https://saltworks.stanford.edu/catalog/druid:sz433yh5927

Should it be combined for display purposes instead?

**Comment by ggeisler** [comment]
What fields exactly are we talking about here? Box, folder, series, subseries? Just box and folder?

If the fields are available separately for facets, I'm not sure it's worth the custom work necessary to concatenate them for the record view. I'd suggest we just stick with what Spotlight already does.

(Just to be clear, in Spotlight the curator picks which fields to display in the each search results view and the record view. For Salt, we'll be the curator, but the point is that the decision on which pages to display which fields is a curator decision, not a development decision, unless we think we need to do something special display-wise for Salt, and I'm not sure that we do.)

**Comment by ndushay** [comment]
I was thinking more that we could:
1.  display the raw value in mods physicalLocation element
2.  tweak the raw value in mods physicalLocation element
in either case, we need to tweak the spotlight configs to show this data at all (it's not gonna be in an existing configured "show" field for the record view.

And since we have to do some special parsing for the facets, we can bundle special parsing for display it at low cost.  But skipping special parsing for display would be an excellent choice.  Then the question becomes:  display the facet values or the raw data.

(Link to raw data (for partially accessioned collection) in slack.)

**Comment by peetucket** [comment]
It is any data currently found in the physical location field in MODs, e.g. "Call Number: SC0340, Accession 2005-101, Box: 34, Folder: 28"

Three of these values (Box, Folder and Series) will be facets to match SaltWorks.  The Call Number will not be a facet, but may be good to display.  So perhaps the answer is to store the full string and just display that, since it will have all the data.  The parsed values will be used for faceting.

**Comment by ggeisler** [comment]
I'd prefer to see the fields on the record view match what the user sees in the facets (i.e., if a user can facet separately on Box, the record view should show the Box field as a separate field) but if it is particularly difficult to do that, including the whole string present in the physical location field in MODs on the record view would be okay, at least for Salt.

**Comment by ndushay** [comment]
I'm closing this in favor of sul-dlss/spotlight-dor-resources#18
