### ISSUE TITLE
Split donor tags into multiple nodes based on commas

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-exhibits-template#44]
- [x] get list of objects that have already been accessioned
- [x] run remediation script to split tags and update contentMetadata
- [x] adjust MODs template
- [x] talk to Ben to update pre-assembly YAML config and MODs template for objects not yet accessioned

**Comment by ndushay** [comment]
example: from http://purl.stanford.edu/vw282gv1740.mods

```
<note displayLabel="Donor tags">Knowledge Systems Laboratory, medical applications, Publishing, Stanford, Stanford Computer Science Department</note>
```
