### ISSUE TITLE
SALT indexing:  document type facet

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-exhibits-template#48]
can we get this or something equivalent via mods genre values?  (not sure - probably want to look at all the genre values once SALT is accessioned?)

e.g.  from http://purl.stanford.edu/vw282gv1740.mods
```
    <genre authority="aat" valueURI="http://vocab.getty.edu/aat/300028579">manuscripts for publication</genre>
```

from http://purl.stanford.edu/qy593db7842.mods
```
    <mods:genre authority="aat" valueURI="http://vocab.getty.edu/aat/300026392">interviews</mods:genre>
```

![document type facets](https://cloud.githubusercontent.com/assets/96775/10530504/6beb498e-735d-11e5-9f1d-1429c5735c5c.png)

**Comment by ndushay** [comment]
@peetucket can you check the salt data spreadsheet and see if this information is going into the genre element (or if it is going anywhere specifically)?

**Comment by ndushay** [comment]
Further info:

this druid is in both: gw545by8468
* new:  
** https://exhibits.stanford.edu/feigenbaum/default-exhibit/catalog?utf8=%E2%9C%93&exhibit_id=default-exhibit&q=lederberg+pcal
** https://exhibits.stanford.edu/feigenbaum/default-exhibit/catalog/gw545by8468
* old
** https://saltworks.stanford.edu/catalog?f[documentType_facet][]=email
** https://saltworks.stanford.edu/catalog/druid:gw545by8468
and seems to have "Document Type" of "manuscript"

http://purl.stanford.edu/gw545by8468.mods
```
<genre authority="aat" valueURI="http://vocab.getty.edu/aat/300149026">electronic mail</genre>
```

**Comment by peetucket** [comment]
yes, the documentType is in the <genre> as noted above.  values may not be exact matches from old to new based on normalization and updating of values by Daniel/Shelley to match controlled vocabs/authorities

**Comment by ndushay** [comment]
in 'genre' you mean, right?

**Comment by peetucket** [comment]
yup, github format issue, fixed it

**Comment by ndushay** [comment]
link to all values for genre fields in so-far-accessioned data in slack
