### ISSUE TITLE
SALT indexing: tagged by donor facet

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-exhibits-template#50]
This information is a MODS note field with displayLabel of "Donor tags".  

The original template to get from the SALT data in spreadsheet format  to MODS  put all the values in a single note field, comma separated.   For indexing, it is far more desirable to have each value in a separate note field.

Pre-requisite steps:
- [x] accessioning stopped
- [x] template changed to make a separate note field for each value (thanks @peetucket ) for uningested items
- [x] @blalbrit will update the template used for ingest
- [x] @blalbrit will start accessioning the rest of the salt data
- [x] remediate multivalued note fields (#44) - IN PROGRESS NOW

Then
- [x] note field with displayLabel "Donor tags" will get indexed into a field suitable for faceting
- [x] spotlight exhibit will be configured to include this field as a facet.

**Comment by ndushay** [comment]
examples:

http://purl.stanford.edu/vw282gv1740.mods
```
<note displayLabel="Donor tags">Knowledge Systems Laboratory, medical applications, Publishing, Stanford, Stanford Computer Science Department</note>
```

http://purl.stanford.edu/jz524jt5425.mods
```
<note displayLabel="Donor tags">1st Accession, AI-IN-Medicine (AIM), BLOCKED-SENSITIVE, SUMEX, WJC_PRIV_SSN</note>
```

**Comment by peetucket** [comment]
Example noted above will be split once remediation is complete.
