### ISSUE TITLE
SALT indexing:  folder name (SALT subseries) facet

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-exhibits-template#52]
saltworks has a Subseries facet:

![subseries facet values 1](https://cloud.githubusercontent.com/assets/96775/10531610/e0e17adc-7368-11e5-8718-ce2808441dc3.png)

![subseries facet values 2](https://cloud.githubusercontent.com/assets/96775/10531611/e4b99716-7368-11e5-9bb7-8578b121da18.png)

**Comment by ndushay** [comment]
A document with a value of "Schlumberger" for this facet, that is in the old and new:  bs912ky4641

http://purl.stanford.edu/bs912ky4641.mods
only has the word in two places:

```
  <titleInfo>
    <title>Research Notes - Schlumberger Limited - Growth Beyond the 80's</title>
  </titleInfo>
  <note type="preferred citation">Call Number: SC0340, Accession: 1986-052, Box: 20, Folder: 44, Title: Schlumberger</note>
```

* old
  * https://saltworks.stanford.edu/catalog/druid:bs912ky4641

* new:
  * https://exhibits.stanford.edu/feigenbaum/default-exhibit/catalog/bs912ky4641

**Comment by ndushay** [comment]
@peetucket is this information in its own column in the spreadsheet?

**Comment by ndushay** [comment]
ah ha:  https://github.com/sul-dlss/salt/blob/0a8d7b88642ebeb2133613bf2f4d5f219c08dd6b/lib/stanford/salt_document.rb#L215-L226

implies it is derived from the dc:coverage string in old salt fedora:

when I grab the actual zotero datastream from this object in salt fedora, I see:

```
  <dc:coverage>Box: 20, Folder: 44, Title: Schlumberger</dc:coverage>
```

hrmmmm.   @peetucket   Is this only glommed at the end of the preferred citation field, or is it anywhere else?

**Comment by peetucket** [comment]
Subseries does not appear in its own column in the spreadsheet.  Those facet values look like they are the "Title:" part of the < note type="preferred citation" >  field

**Comment by peetucket** [comment]
Subseries is really the name of the folder, and is 1:1 relationship with folder/box combos.

**Comment by ndushay** [comment]
done in spotlight-dor-resources and sul-exhibits-templates.   Deploy, index, and voila!
